global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']

  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.47:9100', '192.168.1.48:9100', '192.168.1.49:9100', '192.168.1.50:9100', '192.168.1.51:9100', '192.168.1.52:9100']

  - job_name: 'etcd'
    static_configs:
      - targets: ['192.168.1.50:2379', '192.168.1.51:2379', '192.168.1.52:2379']


  - job_name: 'postgress-exporter'
    static_configs:
      - targets: ['192.168.1.48:9187', '192.168.1.49:9187']