global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['localhost:9093']

  - job_name: 'node'
    static_configs:
      - targets: ['192.168.1.47:9100', '192.168.1.48:9100', '192.168.1.49:9100', '192.168.1.50:9100', '192.168.1.51:9100', '192.168.1.52:9100']

  - job_name: 'etcd'
    static_configs:
      - targets: ['192.168.1.50:2379', '192.168.1.51:2379', '192.168.1.52:2379']


  - job_name: 'postgress-exporter'
    static_configs:
      - targets: ['192.168.1.48:9187', '192.168.1.49:9187']


  - job_name: 'blackbox-exporter'
    static_configs:
      - targets: ['localhost:9115']


  - job_name: blackbox
    metrics_path: /probe
    params:
        module: [http_2xx]
    static_configs:
        - targets:
          - "https://176.109.82.213/swagger/index.html"
    relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - target_label: __address__
          replacement: "192.168.1.47:9115"
        - source_labels: [__meta_dns_name]
          target_label: __param_hostname
        - source_labels: [__meta_dns_name]
          target_label: vhost