{
 "title": "Golden metrics",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(nginx_ingress_controller_nginx_process_connections{state=\"active\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{host=\"raiskii\"}[1m])) by (le))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{status=~\"5..\"}[1m]))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"sre-cource-api\"}[15s]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}